# -*- coding: utf-8 -*-
"""Image Brightness Unit Test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ie1XHLQVPF6m2JkCEEznAh_eudj9mQ80
"""

def get_image_brightness(path):
  """Downloads an image from the bucket and get its mean brightness."""
  import numpy as np
  img = image.imread(path)
  return np.mean(img)
